On failure, restart not just upload, but the whole backup

diff --git a/ibaraki b/ibaraki
--- a/ibaraki
+++ b/ibaraki
@@ -127,25 +127,25 @@ else
         ssh_run "Created $HOST:$TMPDIR." "Can't create $HOST:$TMPDIR." mkdir -p $TMPDIR || quit "\n--- Error communicating $HOST: unable to create working directory!"
         scp_to $0 $TMPDIR/$REMOTENAME || quit "\n--- Error communicating $HOST: unable to upload remote side script!"
 
-        # Run --create
-        ssh_run "Remote script succeeded." "Remote script failed!" $TMPDIR/$REMOTENAME --create $FILE $USER $TMPDIR $ARCHIVER $ARCHPACK $ARCHTEST $ARCHARGS $ARCHEXT $SPECIFY_ARCHIVE_NAME $ENABLE_IONICE $ENABLE_CHECK $DIRECTORIES ||
-            quit "\n--- Error communicating $HOST: unable to run remote side script!"
-
-        # Determine size and checksum
-        echo -e "--- Calculating a checksum:"
-        SRC_SIZE=`ssh_run '' 'Failure' stat --printf=%s $TMPDIR/$FILE.tar.$ARCHEXT 2>&1 | grep -v 'REMOTE CALL'`
-        SRC_MD5=`ssh_run '' 'Failure ' md5sum $TMPDIR/$FILE.tar.$ARCHEXT 2>&1 | grep -v 'REMOTE CALL' | cut -d' ' -f1`
-        echo $HOST:$TMPDIR/$FILE.tar.$ARCHEXT: Size=$SRC_SIZE, MD5=$SRC_MD5.
-        FAILED="no"
-        echo "$SRC_SIZE" | grep -q 'Failure' && FAILED="yes"
-        echo "$SRC_MD5" | grep -q 'Failure' && FAILED="yes"
-        [ "$FAILED" = "yes" ] && quit "\n--- Error communicating $HOST: unable to read backup file!"
-
-        # Copy resulting file back
         SUCCESS="no"
         for ATTEMPT in `seq 1 $ATTEMPTS`
         do
             [ $ATTEMPT -ne 1 ] && echo "TRYING AGAIN"
+
+            # Run --create
+            ssh_run "Remote script succeeded." "Remote script failed!" $TMPDIR/$REMOTENAME --create $FILE $USER $TMPDIR $ARCHIVER $ARCHPACK $ARCHTEST $ARCHARGS $ARCHEXT $SPECIFY_ARCHIVE_NAME $ENABLE_IONICE $ENABLE_CHECK $DIRECTORIES || continue
+
+            # Determine size and checksum
+            echo -e "--- Calculating a checksum:"
+            SRC_SIZE=`ssh_run '' 'Failure' stat --printf=%s $TMPDIR/$FILE.tar.$ARCHEXT 2>&1 | grep -v 'REMOTE CALL'`
+            SRC_MD5=`ssh_run '' 'Failure ' md5sum $TMPDIR/$FILE.tar.$ARCHEXT 2>&1 | grep -v 'REMOTE CALL' | cut -d' ' -f1`
+            echo $HOST:$TMPDIR/$FILE.tar.$ARCHEXT: Size=$SRC_SIZE, MD5=$SRC_MD5.
+            FAILED="no"
+            echo "$SRC_SIZE" | grep -q 'Failure' && FAILED="yes"
+            echo "$SRC_MD5" | grep -q 'Failure' && FAILED="yes"
+            [ "$FAILED" = "yes" ] && continue
+
+            # Copy resulting file back
             echo "--- Getting archive from remote host:"
             mkdir -p "$BACKUPDIR/$HOST" 2>&1
             if scp_from "$TMPDIR/$FILE.tar.$ARCHEXT" "$BACKUPDIR/$HOST/$FILE.tar.$ARCHEXT"
